version: "3.9"
services:
  db17:
    image: postgres:17
    container_name: postgres-17
    ports:
      - "5556:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata17:/var/lib/postgresql/data
volumes:
  pgdata17:
